# Generated by Django 2.0.2 on 2018-02-24 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_auto_20180224_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.Persona')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
            ],
            bases=('master.persona',),
        ),
    ]
