# Generated by Django 2.0.2 on 2018-02-24 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180224_0011'),
        ('nominas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='master.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso_iess',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
