# Generated by Django 2.0.3 on 2018-04-03 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0004_auto_20180307_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cargo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='nominas_report.Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='nominas_report.Empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolpago',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles_pago', to='nominas_report.Contrato'),
            preserve_default=False,
        ),
    ]
