# Generated by Django 2.0.3 on 2018-04-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0005_auto_20180403_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuradetallerolpago',
            name='regla',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso_iess',
            field=models.DateField(blank=True, null=True),
        ),
    ]
