# Generated by Django 2.0.3 on 2018-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0008_merge_20180417_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidadorolpago',
            name='observacion',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
