# Generated by Django 2.0.3 on 2018-04-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0009_auto_20180420_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolpago',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
    ]
