# Generated by Django 2.0.3 on 2018-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0010_auto_20180421_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidadorolpago',
            name='estado',
        ),
        migrations.AddField(
            model_name='consolidadorolpago',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
