# Generated by Django 2.0.3 on 2018-05-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0011_auto_20180421_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuradetallerolpago',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallerolpago',
            name='cantidad',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='detallerolpago',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
