# Generated by Django 2.0.3 on 2018-05-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0012_auto_20180502_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerolpago',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detallerolpago',
            name='cantidad',
            field=models.TextField(blank=True, default='1', null=True),
        ),
    ]
