# Generated by Django 2.0.3 on 2018-05-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0013_auto_20180507_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerolpago',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
