# Generated by Django 2.0.2 on 2018-02-23 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=25, unique=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.FileField(upload_to='')),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
