# Generated by Django 2.0.3 on 2018-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20180227_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleparametrizacion',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='detalleparametrizacion',
            unique_together={('codigo', 'nombre', 'descripcion', 'valor')},
        ),
    ]
