# Generated by Django 2.0.3 on 2018-04-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180403_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='master.Empresa'),
        ),
    ]
