# Generated by Django 2.0.4 on 2018-04-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20180417_0059'),
        ('master', '0006_auto_20180416_1657'),
    ]

    operations = [
    ]
