# Generated by Django 2.0.3 on 2018-03-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_menu_menugroup_menuusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='padre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='seguridad.Menu'),
            preserve_default=False,
        ),
    ]
