# Generated by Django 2.0.3 on 2018-03-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_menu_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='seguridad.Menu'),
        ),
    ]
