# Generated by Django 2.0.3 on 2018-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_menu_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icono',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
